# Generated by Django 2.1.2 on 2019-02-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='netstatus',
            name='geoadress',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='netstatus',
            name='ipadress',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='netstatus',
            name='device',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='netstatus',
            name='updatetime',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
