# Generated by Django 2.1.2 on 2019-02-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netstatus', '0002_auto_20190227_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netstatus',
            name='geoadress',
            field=models.TextField(blank=True, default='Unknown', null=True),
        ),
    ]
